# Generated by Django 4.0.3 on 2022-04-16 11:34

import common.validators
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_content', '0022_alter_ingredient_name_alter_recipe_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredient',
            name='name',
            field=models.CharField(max_length=30, validators=[common.validators.LettersNumbersWhitespacesValidator('(?<![\\s\\W\\D])^([a-zA-Zа-яА-Я0-9]+[\\s]?[a-zA-Zа-яА-Я0-9]+)+$(?![\\s\\W\\D])'), django.core.validators.MinLengthValidator(2)], verbose_name='Име'),
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='price_per_type',
            field=models.DecimalField(decimal_places=3, max_digits=6, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Цена в лв'),
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='type',
            field=models.CharField(choices=[('Kilogram', 'Kilogram'), ('Liter', 'Liter'), ('Piece', 'Piece')], default='Kilogram', max_length=8, verbose_name='за'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='name',
            field=models.CharField(max_length=120, validators=[common.validators.LettersNumbersWhitespacesValidator('(?<![\\s\\W\\D])^([a-zA-Zа-яА-Я0-9]+[\\s]?[a-zA-Zа-яА-Я0-9]+)+$(?![\\s\\W\\D])'), django.core.validators.MinLengthValidator(2)], verbose_name='Име на рецепта'),
        ),
        migrations.AlterField(
            model_name='recipeingredient',
            name='amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6, validators=[django.core.validators.MinValueValidator(1)], verbose_name='Количество в гр./бройка'),
        ),
    ]
